#!/bin/sh
echo "Running flake8 linter..."
flake8 .
if [ $? -ne 0 ]; then
echo "Linting failed! Commit aborted."
exit 1
fi
echo "Running black formatter check..."
black --check .
if [ $? -ne 0 ]; then
echo "Code not formatted properly (black check failed). Commit
aborted."
exit 1
fi  